name: CI Pipeline 

# this pipeline runs on every push or pull request on the main branch 
on:
    push:
        branches:
            - main 
    pull_request: 
        branches:
            - main 

# Checks out the code. Installs dependencies using go mod tidy. 
# Runs all unit tests with go test ./...
# Builds the application into an executable (to-do-list-app-backend)
jobs:
    build:
        runs-on: ubuntu-latest 

        steps:
            # Checkout code 
            - name: Checkout code 
              uses: actions/checkout@v3 
            
            # Set up Go 
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.20

            # Install dependencies
            - name: Install dependencies 
              run: go mod tidy 

            # Run tests 
            - name: Run unit tests 
              run: go test ./... -v 

            # Build application 
            - name: Build application 
              run: go build -o to-do-list-backend main.go

    lint:
      runs-on: ubuntu-latest 

      steps:
        # Checkout code 
        - name: Checkout code 
          uses: actions/checkout@v3 
        
        # Set up Go 
        - name: Set up Go 
          uses: actions/setup-go@v4 
          with:
            go-version: 1.20 
        
        # Run linting 
        - name: Run golangci-lint 
          uses: golangci/golangci-lint-action@v3 
          with:
            version: v1.54.2 
    
    deploy: 
        runs-on: ubuntu-latest 
        needs: [build, lint] 

        steps:
          - name: Checkout code 
            uses: actions/checkout@v3 
        
          - name: Deploy to server 
            run: echo "Deploy stage - Add deployment script or actions here"